app:
  version: ${project.version}
  name: ${project.name}

server:
  error:
    path: '/error'
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: dev
  test:
    constructor:
      autowire:
        mode: all
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:file:./dbdata/imweb;AUTO_SERVER=true;
    driver-class-name: org.h2.Driver
    username: mh
    password: mh
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}|%clr(%-5level)|%clr(%F){cyan}:%L|%clr(%logger{0}){blue}|%clr(%M){magenta}|%msg%n"
  level:
    root: info
    org.example.*: debug